#!/bin/bash
ln -snf /usr/share/zoneinfo/$(curl https://ipapi.co/timezone) /etc/localtime
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible
sudo ansible-pull -U https://github.com/Leenus533/Setup.git --ask-become-pass --ask-vault-pass


