#!/bin/bash
ln -snf /usr/share/zoneinfo/$(curl https://ipapi.co/timezone) /etc/localtime
apt-add-repository -y ppa:ansible/ansible
apt-get update -y
apt-get install -y curl git software-properties-common ansible
ansible-pull -U https://github.com/Leenus533/Setup.git


