- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: Update package manager cache
      when: ansible_os_family == "Debian"
      become: true
      apt:
        update_cache: true

    - name: Update package manager cache 
      when: ansible_os_family == "Archlinux"
      become: true 
      pacman:
        update_cache: yes 
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/google.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/custom.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/display.yml
    - import_tasks: tasks/dotfiles.yml
