- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/google.yml
    - import_tasks: tasks/zsh.yml
