- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    oh_my_zsh_dir: "{{ '/home/' + ansible_user_id + '/.oh-my-zsh' if ansible_distribution != 'MacOSX' else '/Users/' + ansible_user_id + '/.oh-my-zsh' }}"
    zsh_plugins_dir: "{{ oh_my_zsh_dir + '/custom/plugins' }}"
    become_user_id: "{{ ansible_user_id if ansible_distribution == 'MacOSX' else omit }}"
  pre_tasks:
    - name: Update package manager cache
      become: true
      ansible.builtin.package:
        update_cache: true
      when: ansible_distribution != "MacOSX"
      ignore_errors: true
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/custom.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/display.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/google.yml
