- name: Install feh
  become: true
  package:
    name: feh
    state: present
  when: ansible_distribution != "MacOSX"

- name: Copy background to /usr/share/backgrounds/
  become: true
  shell:
    cmd: cp ./background.png /usr/share/backgrounds/
  when: ansible_distribution != "MacOSX"

- name: Swap image names
  command: mv /usr/share/backgrounds/{{ item.old }} /usr/share/backgrounds/{{ item.new }}
  loop:
    - { old: "bChatGPT can make mlackcat.jpg", new: "i3_default_background.jpg.tmp" }
    - { old: "i3_default_background.jpg", new: "blackcat.jpg" }
    - { old: "i3_default_background.jpg.tmp", new: "i3_default_background.jpg" }
  become: true
  tags: background
  when: ansible_distribution == "Archlinux"
  ignore_errors: true

- name: Enable and start systemd-timesyncd service
  become: true
  systemd:
    name: systemd-timesyncd
    state: started
    enabled: yes
  ignore_errors: true
  when: ansible_distribution == "Archlinux"

- name: Install alacritty, neovim 
  become: yes
  become_user: "{{ ansible_user_id if ansible_distribution == 'MacOSX' else omit}}"
  package:
    name:
      - alacritty
      - neovim
    state: present
  ignore_errors: yes

- name: Install docker and go
  become: true
  package:
    name:
      - docker 
      - go 
    state: present
  when: ansible_distribution == "Archlinux"
  ignore_errors: yes

- name: Install wmctrl
  become: true
  package:
    name: wmctrl
    state: present
  when: ansible_distribution != "MacOSX"
