
- name: Install feh
  become: true
  ansible.builtin.package:
    name: feh
    state: present

- name: Copy background to /usr/share/backgrounds/
  become: true
  ansible.builtin.shell:
    cmd: cp ./background.png /usr/share/backgrounds/
  

- name: Swap image names
  command: mv /usr/share/backgrounds/{{ item.old }} /usr/share/backgrounds/{{ item.new }}
  loop:
    - { old: 'blackcat.jpg', new: 'i3_default_background.jpg.tmp' }
    - { old: 'i3_default_background.jpg', new: 'blackcat.jpg' }
    - { old: 'i3_default_background.jpg.tmp', new: 'i3_default_background.jpg' }
  become: true
  tags: background
  ignore_errors: true

- name: Install Alacritty
  become: true
  ansible.builtin.package:
    name: alacritty
    state: present

- name: Install neovim
  become: true
  ansible.builtin.package:
    name: neovim
    state: present

- name: Install go
  become: true
  ansible.builtin.package:
    name: go
    state: present

- name: Install docker
  become: true
  ansible.builtin.package:
    name: docker
    state: present
