
- name: Install feh
  become: true
  pacman:
    name: feh
    state: present

- name: Copy background to /usr/share/backgrounds/
  ansible.builtin.shell:
    cmd: cp ./background.png /usr/share/backgrounds/
  tags: i3

- name: install visual studio code using yay
  become: yes
  ansible.builtin.command:
    cmd: yay -S --noconfirm visual-studio-code-bin
  when: ansible_os_family == "Archlinux"

- name: Install Alacritty
  become: true
  pacman:
    name: alacritty
    state: present

- name: Install neovim
  become: true
  pacman:
    name: neovim
    state: present