
- name: Install feh
  become: true
  pacman:
    name: feh
    state: present

- name: Copy background to /usr/share/backgrounds/
  become: true
  ansible.builtin.shell:
    cmd: cp ./background.png /usr/share/backgrounds/
  tags: i3

- name: Install Alacritty
  become: true
  pacman:
    name: alacritty
    state: present

- name: Install neovim
  become: true
  pacman:
    name: neovim
    state: present

- name: Install go
  become: true
  pacman:
    name: go
    state: present