- name: Install autorandr
  become: yes
  ansible.builtin.package:
    name: autorandr
    state: present
  tags: display

- name: Configure display settings
  ansible.builtin.command:
    cmd: xrandr --output DP-2 --primary --mode 1920x1080 --rate 237.76 --output DP-0 --mode 1920x1080 --rate 144.00 --right-of DP-2
  tags: display

- name: Save display configuration
  ansible.builtin.command:
    cmd: autorandr --save workstation
  tags: display
  become: yes
  become_user: copperr
  ignore_errors: true

