- name: Clone Dotfiles Repository
  git:
    repo: git@github.com:Leenus533/.dotfiles.git
    dest: ~/.dotfiles
    version: main
  become_user: copperr
  tags: dotfiles

- name: Install stow
  package:
    name: stow
    state: present
  become: yes
  tags: dotfiles

- name: Stow dotfiles
  ansible.builtin.shell:
    cmd: stow -t ~ -d ~/.dotfiles
  become_user: copperr
  tags: dotfiles