- name: Add GitHub to known hosts
  ansible.builtin.known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    state: present

- name: Clone Dotfiles Repository
  git:
    repo: git@github.com:Leenus533/.dotfiles.git
    dest: ~/.dotfiles
    version: main
    force: yes
  become_user: "{{ ansible_user_id }}"
  tags: dotfiles

- name: Install stow
  ansible.builtin.package:
    name: stow
    state: present
  become: yes
  become_user: "{{ become_user_id }}"
  tags: dotfiles
  ignore_errors: yes

- name: Remove .zshrc file
  ansible.builtin.file:
    path: ~/.zshrc
    state: absent
  tags: dotfiles

- name: Remove .i3/config file
  ansible.builtin.file:
    path: ~/.i3/config
    state: absent
  tags: dotfiles

- name: Stow dotfiles
  ansible.builtin.shell:
    cmd: stow -t ~ -d ~/.dotfiles
  become_user: "{{ ansible_user_id }}"
  tags: dotfiles
  ignore_errors: true
