- name: Add GitHub to known hosts
  known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    state: present

- name: Clone Dotfiles Repository
  git:
    repo: git@github.com:Leenus533/.dotfiles.git
    dest: ~/.dotfiles
    version: main
    force: yes
  become_user: "{{ ansible_user_id }}"
  tags: dotfiles

- name: Install stow
  package:
    name: stow
    state: present
  become: yes
  become_user: "{{ become_user_id }}"
  tags: dotfiles
  ignore_errors: yes

- name: Remove .zshrc file
  file:
    path: ~/.zshrc
    state: absent
  tags: dotfiles

- name: Remove .i3/config file
  file:
    path: ~/.i3/config
    state: absent
  tags: dotfiles

- name: Stow dotfiles
  shell:
    cmd: stow .
    chdir: /home/{{ ansible_user_id }}/.dotfiles
  become_user: "{{ ansible_user_id }}"
  tags: dotfiles

- name: Create symbolic for nvim configuration
  file:
    src: "/home/{{ ansible_user_id }}/.config/nvim"
    dest: /root/.config/nvim
    state: link
  become: yes
  tags: dotfiles
