- name: Install yay (if not already present)  # For installing Google Chrome on Arch
  become: yes
  pacman:
    name: yay
    state: present
  when: ansible_os_family == "Archlinux"  # Only for Arch

  
- name: Install Google Chrome (from AUR) using yay # Using AUR on Arch
  become: yes
  ansible.builtin.command:
    cmd: yay -S --noconfirm google-chrome-stable
  when: ansible_os_family == "Archlinux"  # Only for Arch

- name: Install Google Chrome (for Ubuntu/Debian)  # Using apt on Ubuntu/Debian
  become: yes
  apt:
    name: google-chrome-stable
    state: present
  when: ansible_os_family == "Debian"  # Only for Ubuntu/Debian
