- name: Install yay (if not already present)
  become: true
  pacman:
    name: yay
    state: present
  when: ansible_os_family == "Archlinux"

- name: Install discord, visual-studio-code using yay
  become_user: "{{ ansible_user_id }}"
  command:
    cmd: "yay -S --noconfirm {{ item }}"
  loop:
    - discord
    - visual-studio-code-bin
  when: ansible_os_family == "Archlinux"
  ignore_errors: true
