- name: Install yay (if not already present)
  become: yes
  pacman:
    name: yay
    state: present
  when: ansible_os_family == "Archlinux" 

  
- name: Install Google Chrome (from AUR) using yay
  ansible.builtin.command:
    cmd: yay -S --noconfirm google-chrome-stable
  when: ansible_os_family == "Archlinux" 

- name: Install Google Chrome (for Ubuntu/Debian)
  become: yes
  apt:
    name: google-chrome-stable
    state: present
  when: ansible_os_family == "Debian"

- name: Install Discord for Aur
  become_user: copperr
  ansible.builtin.command:
    cmd: yay -S --noconfirm discord
  when: ansible_os_family == "Archlinux"

- name: Install Discord for Ubuntu/Debian
  become: yes
  apt:
    name: discord
    state: present
  when: ansible_os_family == "Debian"

- name: install visual studio code using yay
  become_user: copperr
  ansible.builtin.command:
    cmd: yay -S --noconfirm visual-studio-code-bin
  when: ansible_os_family == "Archlinux"

- name: install youtube music app
  ansible.builtin.command:
    cmd: yay -S --noconfirm youtube-music
  when: ansible_os_family == "Archlinux"
