- name: Install yay (if not already present)
  become: yes
  pacman:
    name: yay
    state: present
  when: ansible_os_family == "Archlinux" 

  
- name: Install Google Chrome (from AUR) using yay
  become: yes
  ansible.builtin.command:
    cmd: yay -S --noconfirm google-chrome-stable
  when: ansible_os_family == "Archlinux" 

- name: Install Google Chrome (for Ubuntu/Debian)
  become: yes
  apt:
    name: google-chrome-stable
    state: present
  when: ansible_os_family == "Debian"
