- name: Install core Node.js dependencies
  become: yes
  become_user: "{{ become_user_id }}"
  package:
    name: [nodejs, npm, unzip]
    state: present
  tags: node
  ignore_errors: true

- name: Install n (Node Version Manager)
  become: yes
  become_user: "{{ become_user_id }}"
  npm:
    name: n
    global: true
  tags: node
  ignore_errors: true

- name: Install latest Node.js using n
  become: yes
  become_user: "{{ become_user_id }}"
  shell: n latest
  tags: node
  ignore_errors: true

- name: Install bun
  become_user: "{{ ansible_user_id }}"
  shell:
    cmd: "curl -fsSL https://bun.sh/install | bash"
  tags: node
  ignore_errors: true

- name: Install TypeScript
  become: yes
  become_user: "{{ become_user_id }}"
  npm:
    name: typescript
    global: true
  tags: node
  ignore_errors: true

- name: Install Nodemon
  become: yes
  become_user: "{{ become_user_id }}"
  npm:
    name: nodemon
    global: true
  tags: node
  ignore_errors: true
