- name: Install core Node.js dependencies
  become: yes
  package:
    name: [nodejs, npm]  
    state: present 
  when: ansible_os_family in ["Debian", "Archlinux"] 
  tags: node  

- name: Install n (Node Version Manager)
  become: yes
  npm:
    name: n
    global: true
  tags: node

- name: Install latest Node.js using n
  become: yes 
  shell: n latest
  tags: node

- name: Install unzip
  become: yes
  package:
    name: unzip
    state: present
  tags: node
  
- name: Install bun
  become: yes 
  ansible.builtin.shell:
    cmd: "curl -fsSL https://bun.sh/install | bash"
  tags: node

- name: Install TypeScript
  become: yes
  npm:
    name: typescript
    global: true
  tags: node

- name: Install Nodemon
  become: yes
  npm:
    name: nodemon
    global: true
  tags: node
