- name: Install core Node.js dependencies
  become: yes
  ansible.builtin.package:
    name: [nodejs, npm, unzip]  
    state: present 
  tags: node 
  ignore_errors: true

- name: Install n (Node Version Manager)
  become: yes
  npm:
    name: n
    global: true
  tags: node
  ignore_errors: true

- name: Install latest Node.js using n
  become: yes 
  shell: n latest
  tags: node
  ignore_errors: true
  
- name: Install bun
  become_user: copperr
  ansible.builtin.shell:
    cmd: "curl -fsSL https://bun.sh/install | bash"
  tags: node
  ignore_errors: true

- name: Install TypeScript
  become: yes
  npm:
    name: typescript
    global: true
  tags: node
  ignore_errors: true

- name: Install Nodemon
  become: yes
  npm:
    name: nodemon
    global: true
  tags: node
  ignore_errors: true
