- name: Install ZSH
  become: yes
  ansible.builtin.package:
    name: zsh
    state: present
  tags: zsh

- name: Change default shell to zsh for copperr
  ansible.builtin.command:
    cmd: chsh -s /bin/zsh copperr
    become: yes
  tags: zsh

- name: Check that the ~/.oh-my-zsh directory exists
  ansible.builtin.stat:
    path: /home/copperr/.oh-my-zsh
  register: oh_my_stats
  tags: zsh

- name: Install Oh-My-Zsh
  ansible.builtin.shell:
    cmd: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: zsh
  when: oh_my_stats.stat.exists == False
  become_user: copperr

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "/home/copperr/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: zsh

- name: Install tmux
  become: yes
  ansible.builtin.package:
    name: tmux
    state: present
  tags: zsh

- name: Install fzf
  become: yes
  ansible.builtin.package:
    name: fzf
    state: present
  tags: zsh

- name: Add alias for fzf
  ansible.builtin.lineinfile:
    path: /home/copperr/.zshrc
    line: "alias sd='cd ~ && cd $(find * -type d | fzf)'"
  tags: zsh

- name: Ensure ~/.local/bin/ directory exists
  ansible.builtin.file:
    path: "/home/copperr/.local/bin/"
    state: directory
    mode: "0755"
  tags: zsh

- name: Copy tmux-sessionizer to $HOME/bin/
  ansible.builtin.copy:
    src: ./tmux-sessionizer
    dest: "/home/copperr/.local/bin/tmux-sessionizer"
    mode: "0755"
  tags: zsh

- name: Add Shortcut
  ansible.builtin.lineinfile:
    path: /home/copperr/.zshrc
    line: "bindkey -s '^f' 'tmux-sessionizer\n'"
  tags: zsh

- name: Install autorandr
  become: yes
  ansible.builtin.package:
    name: autorandr
    state: present
  tags: zsh
