- name: Install ZSH and curl
  become: yes
  become_user: "{{ become_user_id }}"
  package:
    name:
      - zsh
      - curl
    state: present
  tags: zsh

- name: Change default shell to zsh for current user
  command:
    cmd: chsh -s /bin/zsh {{ ansible_user_id }}
  become: yes
  tags: zsh

- name: Check that the ~/.oh-my-zsh directory exists
  stat:
    path: "{{ oh_my_zsh_dir }}"
  register: oh_my_stats
  tags: zsh

- name: Install Oh-My-Zsh
  shell:
    cmd: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  become_user: "{{ ansible_user_id }}"
  tags: zsh
  when: oh_my_stats.stat.exists == False

- name: Install zsh-autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ zsh_plugins_dir }}/zsh-autosuggestions"
  tags: zsh
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: Clone zsh-fzf-history-search repository
  git:
    repo: "https://github.com/joshskidmore/zsh-fzf-history-search.git"
    dest: "{{ zsh_plugins_dir }}/zsh-fzf-history-search"
  tags: zsh
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: Install tmux, fzf, zoxide
  become: yes
  become_user: "{{ become_user_id }}"
  package:
    name:
      - tmux
      - fzf
      - zoxide
    state: present
  tags: zsh
  ignore_errors: yes

- name: Clone tmux plugin manager repository
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "/home/{{ ansible_user_id }}/.tmux/plugins/tpm"
    clone: yes
    update: yes
  become: no
