- name: Install ZSH
  become: yes
  ansible.builtin.package:
    name: zsh
    state: present
  tags: zsh

- name: Change default shell to zsh for copperr
  ansible.builtin.command:
    cmd: chsh -s /bin/zsh copperr
  become: yes
  tags: zsh

- name: Check that the ~/.oh-my-zsh directory exists
  ansible.builtin.stat:
    path: /home/copperr/.oh-my-zsh
  register: oh_my_stats
  tags: zsh

- name: Install Oh-My-Zsh
  ansible.builtin.shell:
    cmd: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: zsh
  when: oh_my_stats.stat.exists == False
  become_user: copperr

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ ZSH_CUSTOM | default('~/.oh-my-zsh/custom') }}/plugins/zsh-autosuggestions"
  tags: zsh
  become: yes
  become_user: copperr


- name: Clone zsh-fzf-history-search repository
  ansible.builtin.git:
    repo: "https://github.com/joshskidmore/zsh-fzf-history-search.git"
    dest: "{{ ZSH_CUSTOM | default('~/.oh-my-zsh/custom') }}/plugins/zsh-fzf-history-search"
  tags:
    - zsh
  become: yes
  become_user: copperr


- name: Install tmux
  become: yes
  ansible.builtin.package:
    name: tmux
    state: present
  tags: zsh

- name: Install fzf
  become: yes
  ansible.builtin.package:
    name: fzf
    state: present
  tags: zsh

- name: Install zoxide
  become: yes
  ansible.builtin.package:
    name: zoxide
    state: present
  tags: zsh